const String baseUrlPath = 'http://192.168.1.6:4000/api/v1';
const String paymentbaseUrlPath = 'https://accept.paymob.com/api';
const String placesAutocompeleteUrlPath ="https://maps.googleapis.com/maps/api/place/autocomplete/json";
const String placesUrlPath = "https://maps.googleapis.com/maps/api/place/details/json";
const String loginEndPoint = '/users/login';
const String registerEndPoint = '/users/register';
const String forgotPasswordEndPoint = '/users/password/forgot';
const String resetPasswordEndPoint = "/users/password/reset/";
const String profileEndPoint = '/users/me';
const String updateProfileEndPoint = '/users/profile/update';
const String updatePasswordEndPoint = '/users/password/update';
const String productsEndPoint = '/products';
const String reviewEndPoint ='/product/review';
const String newOrderEndPoint ='/order/new';
const String requestAuthEndPoint ='/auth/tokens';
const String requestOrderEndPoint ='/ecommerce/orders';
const String requestPaymentEndPoint ='/acceptance/payment_keys';
String? token;